import React from "react"
import type { Metadata } from "next"
import type { Page } from '@/types'

import "./globals.css"
import { getPages } from "@/utils/contentful"
import { Inter, Playpen_Sans } from "next/font/google"

import Header from "../components/Header"

const inter = Inter({ subsets: ["latin"] })
const pacifico = Playpen_Sans({ weight: "400", subsets: ["latin"], variable: "--font-pacifico" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { slug: string }
}>) {
  const pages: Page[] = await getPages()

  return (
    <html lang="en">
      <body className={`${inter.className} ${pacifico.variable}`}>
        <Header pages={pages} slug={params.slug} />
        {children}
      </body>
    </html>
  )
}
