import type { Metadata } from "next"
import "../globals.css"
import React from "react"
import { getPageTitles } from "@/utils/contentful"

import Header from "../../components/Header"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: { slug: string }
}>) {
  const pages = await getPageTitles()

  return (
    <React.Fragment>
      <Header pages={pages} slug={params.slug} />
      {children}
    </React.Fragment>
  )
}
